version: '4.28.0'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - movies_network

  movieslib:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/moviesdb
    networks:
      - movies_network

volumes:
  mongodb_data:

networks:
  movies_network: